[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[build.nixpacksConfig]
packageManager = "npm"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5